
  /events:
    get:
     summary: Get all eventss
     tags: [events]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/events'
 
    post:
      summary: Create events
      tags: [events]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/events'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events'
 
  /events/{id}:
    get:
      summary: Get events by id
      tags: [events]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events'
 
    put:
      summary: Edit events
      tags: [events]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/events'
 
    delete:
      summary: Delete events
      tags: [events]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  components:
    schemas:
  
      events:
        type: object
        properties:
      
          id:
            type: string
          location:
            type: string
          date:
            type: string
          user:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          password:
            type: string